if (NOT DEFINED __COMMON_INCLUDE__)

set(__COMMON_INCLUDE__)
set(COMMON_INCLUDE_DIR ${CMAKE_BINARY_DIR}/include/common)
set(COMMON_LIBRARY_DIR ${CMAKE_BINARY_DIR}/lib/common)
set(COMMON_BINRARY_DIR ${CMAKE_BINARY_DIR}/bin/common)
set(COMMON_LIBS common)

list(APPEND MODULE_INCLUDE_DIR ${COMMON_INCLUDE_DIR})
list(APPEND MODULE_LIBRARY_DIR ${COMMON_LIBRARY_DIR})
list(APPEND MODULE_LIBS ${COMMON_LIBS})

endif (NOT DEFINED __COMMON_INCLUDE__)